### ISSUE TITLE
Sample Grafana dashboard

### ISSUE THREAD

**Issue by Mehonoshin** [kostiantyn-nemchenko/ansible-role-mongodb-exporter#3]
Hey!

Thank you for this project.
I came across this role, and I wonder if you have any sample Grafana dashboard that can easily display the necessary metrics collected by the exporter.

I know that this is just an ansible wrapper for the exporter, but unfortunately, the exporter itself does not have any sample dashboard too. 

In case you don't have, I can probably build something by myself and share it.

**Comment by kostiantyn-nemchenko** [comment]
Hey @Mehonoshin !
Since this is an ansible wrapper for exporter by *Percona* I'm sure you'll find their [grafana-dashboards](https://github.com/percona/grafana-dashboards/tree/master/dashboards) repository useful for you.
